name: Python Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        python_version: ["3.11", "3.10", "3.9", "3.8"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install poetry
        run: |
          python -m pip install pip wheel pipx --upgrade
          pipx install poetry

      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: poetry

      - name: Install Python Dependencies
        run: poetry install --all-extras

      - name: Generate Code
        run: poetry run python build.py

      - name: Run Tests
        run: poetry run pytest -v

  docs:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "19"
          cache: npm

      - name: Install poetry
        run: |
          python -m pip install pip wheel pipx --upgrade
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: poetry

      - name: Install Python Dependencies
        run: poetry install

      - name: Install Node Dependencies
        run: npm install

      - name: Build Docs
        run: poetry run python build.py --docs

  # does not support 2.5.0
  # validate-apispec:
  #   runs-on: ubuntu-latest
  #   if: "!contains(github.event.head_commit.message, 'ci skip')"

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Validate AsyncAPI Spec
  #       uses: WaleedAshraf/asyncapi-github-action@v0.0.9
  #       with:
  #         filepath: bell/avr/mqtt/asyncapi.yml
